// <auto-generated />
using System;
using BE_ConsilierInteligent.DataAccess.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE_ConsilierInteligent.DataAccess.Migrations
{
    [DbContext(typeof(ConsilierContext))]
    partial class ConsilierContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Chestionar", b =>
                {
                    b.Property<int>("id_chestionar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_chestionar"));

                    b.Property<string>("denumire_test")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("id_consilier")
                        .HasColumnType("int");

                    b.HasKey("id_chestionar");

                    b.HasIndex("id_consilier");

                    b.ToTable("Chestionar");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Consilier", b =>
                {
                    b.Property<int>("id_consilier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_consilier"));

                    b.Property<int?>("id_utilizator")
                        .HasColumnType("int");

                    b.HasKey("id_consilier");

                    b.HasIndex("id_utilizator");

                    b.ToTable("Consilier");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Elev", b =>
                {
                    b.Property<int>("id_elev")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_elev"));

                    b.Property<int?>("id_utilizator")
                        .HasColumnType("int");

                    b.HasKey("id_elev");

                    b.HasIndex("id_utilizator");

                    b.ToTable("Elev");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Intrebare", b =>
                {
                    b.Property<int>("id_intrebare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_intrebare"));

                    b.Property<string>("Formulare_intrebare")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("id_chestionar")
                        .HasColumnType("int");

                    b.HasKey("id_intrebare");

                    b.HasIndex("id_chestionar");

                    b.ToTable("Intrebare");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Raport", b =>
                {
                    b.Property<int>("id_raport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_raport"));

                    b.Property<int>("id_solutie")
                        .HasColumnType("int");

                    b.HasKey("id_raport");

                    b.HasIndex("id_solutie");

                    b.ToTable("Raport");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Raspuns", b =>
                {
                    b.Property<int>("id_raspuns")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_raspuns"));

                    b.Property<int>("Intrebareid_intrebare")
                        .HasColumnType("int");

                    b.Property<int>("ResponseText")
                        .HasColumnType("int");

                    b.Property<int?>("id_intrebare")
                        .HasColumnType("int");

                    b.HasKey("id_raspuns");

                    b.HasIndex("Intrebareid_intrebare");

                    b.ToTable("Raspuns");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Sectiuni_Raport", b =>
                {
                    b.Property<int>("id_sectiune_Raport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_sectiune_Raport"));

                    b.Property<int>("id_raport")
                        .HasColumnType("int");

                    b.Property<int>("id_sectiune_tip_Raport")
                        .HasColumnType("int");

                    b.HasKey("id_sectiune_Raport");

                    b.HasIndex("id_raport");

                    b.HasIndex("id_sectiune_tip_Raport");

                    b.ToTable("Sectiuni_Raport");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Sectiuni_Tip_Raport", b =>
                {
                    b.Property<int>("id_sectiune_tip_Raport")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_sectiune_tip_Raport"));

                    b.Property<string>("denumire_sectiune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scurta_descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_sectiune_tip_Raport");

                    b.ToTable("Sectiuni_Tip_Raport");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Solutie", b =>
                {
                    b.Property<int>("id_solutie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_solutie"));

                    b.Property<string>("denumire_solutie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_solutie");

                    b.ToTable("Solutie");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Solutii_Training", b =>
                {
                    b.Property<int>("id_solutii")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_solutii"));

                    b.Property<int?>("id_chestionar")
                        .HasColumnType("int");

                    b.Property<int>("id_solutie")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_1")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_10")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_11")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_12")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_2")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_3")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_4")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_5")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_6")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_7")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_8")
                        .HasColumnType("int");

                    b.Property<int>("intrebare_9")
                        .HasColumnType("int");

                    b.HasKey("id_solutii");

                    b.HasIndex("id_chestionar");

                    b.HasIndex("id_solutie");

                    b.ToTable("Solutii_Training");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Utilizator", b =>
                {
                    b.Property<int>("id_utilizator")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_utilizator"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nume")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("parola")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("prenume")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("id_utilizator");

                    b.ToTable("Utilizator");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Chestionar", b =>
                {
                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Consilier", "Consilier")
                        .WithMany()
                        .HasForeignKey("id_consilier");

                    b.Navigation("Consilier");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Consilier", b =>
                {
                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("id_utilizator");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Elev", b =>
                {
                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Utilizator", "Utilizator")
                        .WithMany()
                        .HasForeignKey("id_utilizator");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Intrebare", b =>
                {
                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Chestionar", "Chestionar")
                        .WithMany()
                        .HasForeignKey("id_chestionar");

                    b.Navigation("Chestionar");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Raport", b =>
                {
                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Solutie", "Solutie")
                        .WithMany()
                        .HasForeignKey("id_solutie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Solutie");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Raspuns", b =>
                {
                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Intrebare", "Intrebare")
                        .WithMany()
                        .HasForeignKey("Intrebareid_intrebare")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intrebare");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Sectiuni_Raport", b =>
                {
                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Raport", "Raport")
                        .WithMany()
                        .HasForeignKey("id_raport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Sectiuni_Tip_Raport", "Sectiuni_Tip_Raport")
                        .WithMany()
                        .HasForeignKey("id_sectiune_tip_Raport")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Raport");

                    b.Navigation("Sectiuni_Tip_Raport");
                });

            modelBuilder.Entity("BE_ConsilierInteligent.DataAccess.Entities.Solutii_Training", b =>
                {
                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Chestionar", "Chestionar")
                        .WithMany()
                        .HasForeignKey("id_chestionar");

                    b.HasOne("BE_ConsilierInteligent.DataAccess.Entities.Solutie", "Solutie")
                        .WithMany()
                        .HasForeignKey("id_solutie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chestionar");

                    b.Navigation("Solutie");
                });
#pragma warning restore 612, 618
        }
    }
}
